%\VignetteIndexEntry{BioCro Workshop I: Using BioCro with the Standard Module Library}
%\VignettePackage{BioCro}
%\VignetteEngine{knitr::knitr}

% See the following pages for more information about the LaTeX
% problems addressed by the following chunk:
%
% - https://tex.stackexchange.com/questions/148188/knitr-xcolor-incompatible-color-definition
% - https://github.com/yihui/knitr/commit/b31228012419e0365ff33e18ef53fd7be7148e38
%
%
% This chunk must explicitly set eval=TRUE (the default) to ensure
% that this chunk is evaluated, even when eval has been set to FALSE
% at the global level, as in the R-CMD-check GitHub workflow.

<<solve_latex_color_problems, include = FALSE, eval = TRUE>>=

## Versions of knitr before 1.39 used the color package, but we want
## to use xcolor instead (together with the "dvipsnames" option), so
## we use a hook to do a substitution.  (This hook is a no-op for
## knitr version 1.39, assuming the color package is not explicitly
## used by the Rnw file.)

knitr::knit_hooks$set(document = function(x) {
  sub('\\usepackage[]{color}', '\\usepackage[dvipsnames]{xcolor}', x, fixed = TRUE)
})

## Version 1.39 of knitr *does* use the xcolor package, but we still
## have to set it to use the dvipsnames option.  (This option setting
## is a no-op for knitr versions before 1.39, assuming the xcolor
## package is not explicitly used by the Rnw file.)

knitr::opts_knit$set(latex.options.xcolor = 'dvipsnames')
@

\documentclass[10pt,letterpaper,oneside]{article}

\usepackage[utf8]{inputenc}

\usepackage[scaled]{helvet}

\usepackage[T1]{fontenc}

\usepackage[margin=1.0in]{geometry}

\usepackage{graphicx}

\usepackage{amsmath}

\usepackage{amsfonts}

\usepackage{booktabs}

\usepackage{tcolorbox}

\usepackage[colorlinks=true]{hyperref}
\hypersetup{
	pdftitle={BioCro Workshop I: Using BioCro with the Standard Module Library},
	pdfauthor={BioCro Development Team},
	colorlinks=true,
	linkcolor=Blue,
	citecolor=Blue,
	filecolor=Blue,
	urlcolor=Maroon
}

\usepackage[
  backend=bibtex,
  style=authoryear,
  doi=true,
	url=false,
	isbn=false,
	eprint=false,
	date=year,
	texencoding=utf8,
	bibencoding=utf8,
  backref=true
]{biblatex}

\bibliography{references/workshop_I}

\title{BioCro Workshop I: Using BioCro with the Standard Module Library}

\author{BioCro Development Team}

% Use circles instead of dashes in the second level of an `itemize` environment
\renewcommand{\labelitemii}{$\circ$}

% Make sure Helvetica is used throughout the document
% (see https://www.sascha-frank.com/Fonts/Helvetica.html)
\renewcommand\familydefault{\sfdefault}

\newcommand{\nooutput}{There shouldn't be any output from this code.}

\newtcolorbox{mybox}[2][red]{
  colback = shadecolor,
  coltitle = shadecolor,
  colframe = #1!75!black,
  fonttitle = \bfseries,
  title={#2}
}

\newenvironment{boxEnv}[2][red]{
  % begin code
  \noindent
  \begin{mybox}[#1]{#2}
  \begin{minipage}{0.92\columnwidth}
}{
  % end code
  \end{minipage}
  \end{mybox}
  \bigskip
}

\newenvironment{boxCode}{\begin{boxEnv}[darkgray]{Code to run in R}}{\end{boxEnv}}
\newenvironment{boxCodeOptional}{\begin{boxEnv}[gray]{Code to (optionally) run in R}}{\end{boxEnv}}
\newenvironment{boxOutput}{\begin{boxEnv}[teal]{Expected output from R}}{\end{boxEnv}}
\newenvironment{boxExercise}{\begin{boxEnv}[violet]{Exercise}}{\end{boxEnv}}

\begin{document}

\maketitle

\begin{center}
  \includegraphics[width=0.5\textwidth]{workshop_I/biocro_logo.pdf}
\end{center}

% Set things up for R evaluation:
<<preliminaries, echo = FALSE>>=
knitr::opts_chunk$set(error = FALSE) # do stop on errors so we can immediately
                                     # identify problems with the vignette code
knitr::opts_chunk$set(fig.width=5, fig.height=3)
@

<<loading_packages, echo = FALSE, error = FALSE>>=
# Load required packages
library(BioCro)
library(lattice)
library(dfoptim)
library(deSolve)

# Check the BioCro version
expected_version  <- '3.2.0-5'
installed_version <- as.character(packageVersion('BioCro'))

if (compareVersion(expected_version, installed_version) != 0) {
  warning(
    'This script was written for BioCro version ', expected_version,
    ' but version ', installed_version,
    ' is installed; this may cause unexpected errors to occur.'
  )
}
@

<<version_info, echo = FALSE, comment = ''>>=
# Show the current commit hash and the date of that commit.
cat(
  paste0(
    system2('git',
            args = c('show',
                     '-s',
                     '--format="This document was generated from the version of BioCro specified as follows:%n%nCommit Hash: %h%nDate: %aD"'
                    ),
            stdout = TRUE
    ),
    sep = '',
    collapse = '\n'
  ),
  "\nBranch:",
  system2('git',
          args = c('branch',
                   '--show-current'),
          stdout = TRUE
  ),
  "\n"
)
@

\newpage

\tableofcontents

\newpage

\section{About this Workshop}

\begin{itemize}
  \item This workshop was originally held on May 13, 2022 as part of the
  \href{https://cropsinsilico.org/2022-annual-meeting/}{Crops in Silico Symposium}.

  \item Since then, it has been updated following changes to BioCro syntax and
  other new developments.

  \item To use the workshop on your own, try running the code snippets on your
  machine, and complete the exercises to test your understanding.
\end{itemize}

\noindent Throughout this document, look out for the following types of boxes:

\bigskip

\begin{boxCode}
  This indicates a code snippet that should be run in R. Copy it from this
  document and paste it into the R terminal.
\end{boxCode}

\begin{boxCodeOptional}
  This indicates a code snippet that can optionally be run in R.
\end{boxCodeOptional}

\begin{boxOutput}
  This will come after a code snippet, and will show the expected output from
  the code. Use this to check whether you have successfully run the code.
\end{boxOutput}

\begin{boxExercise}
  This will be a suggestion for a task you should be able to complete, and will
  often be based on one or more previous code snippets.
\end{boxExercise}

\newpage

\section{Introduction}

\subsection{Essential information about BioCro}

\begin{itemize}
  \item BioCro is a software package for modular crop growth simulations.

  \item It can also be thought of as a general-purpose tool for defining and
  solving sets of ordinary differential equations.

  \item We have published a paper describing it in \textit{in silico Plants}
  (\cite{lochocki_biocro_2022}), and there is also a
  \href{https://ripe.illinois.edu/press/press-releases/illinois-team-significantly-improves-biocro-software-growing-virtual-crops}{press release about the paper}
  with some additional information.

  \item BioCro is written in \texttt{C++} but has a convenient \texttt{R}
  interface that we will be using today.

  \begin{itemize}
    \item R provides many possible avenues for inputting data and analyzing
    results.

    \item The BioCro R package is available on
    \href{https://cran.r-project.org/package=BioCro}{CRAN}.

  \end{itemize}

  \item BioCro is free and open-source, with the full source code available via
  a public GitHub repository: \url{https://github.com/biocro/biocro}.

  \item Automated tests ensure that the code does not break following any
  changes.

  \item All BioCro documentation can be accessed at \url{https://biocro.org}.
\end{itemize}

\subsection{What do we mean by modular modeling?}

\begin{itemize}
  \item Writing differential equation models is straightforward in itself, but
  for modeling crops, a couple of problems commonly appear:

  \begin{itemize}
    \item Many crops share components, so code is duplicated in many places.

    \item There are different ways to model the same process, but there isn't a
    way to easily choose between them.
  \end{itemize}

  \item Named sets of equations provide a way to easily select and reuse pieces
  of models, and they are a central feature of BioCro that allows us to avoid
  these issues.

  \item A more detailed description of BioCro's approach to modular modeling can
  be found in Section \ref{sec_modular}.
\end{itemize}

\begin{center}
  \includegraphics[width=\textwidth]{workshop_I/biocro_framework.pdf}
\end{center}

\subsection{How did we get here?}

\begin{itemize}
  \item BioCro began its life in the early 1990s as a program called WIMOVAC
  (\cite{humphries_wimovac_1995}). Crops were added over the years and the
  software was rewritten in C, eventually becoming BioCro
  (\cite{miguez_modeling_2012}).

  \item Several years ago, Justin McGrath began modifying BioCro to reduce
  duplicated code and make it more flexible, resulting in the new version of
  BioCro we will be using today (\cite{lochocki_biocro_2022}).

  \item The primary developers in recent years include Justin McGrath, Ed
  Lochocki, Yufeng He, Scott Oswald, Scott Rohde, Deepak Jaiswal, Megan
  Matthews, Fernando Miguez, and Steve Long.
\end{itemize}

\subsection{What does BioCro enable us to do? \label{sec_biocro_enable}}

\begin{itemize}
  \item The latest versions of BioCro were created with a few important
  philosophical tenets in mind:

  \begin{itemize}
    \item Models are sets of equations.

    \item No equation is special.
  \end{itemize}

  \item This mindset has produced a flexible structure where model components
  can be added, removed, swapped, or redefined in a straightforward way. This
  makes BioCro particularly well-suited for operations like the following:

  \begin{itemize}
    \item \textbf{Sensitivity analysis}: Identify parameters that are most
    important for determining certain outputs.

    \item \textbf{Parameterization}: Find parameter values that best reproduce
    the available experimental data.

    \item \textbf{Quanatitative comparisons between alternate versions of model
    components}: For example, by quantifying which carbon allocation model best
    reproduces the available experimental data.

    \item \textbf{Sensor integration}: Replace calculation of a variable with
    measurements from a sensors.

    \item \textbf{Predictive power}: Quantify changes in accuracy as model
    components are updated or replaced.

    \item \textbf{Learning and teaching}: Examine model components on their
    own or in the context of a larger model.

  \end{itemize}
\end{itemize}

\begin{center}
  \includegraphics[width=\textwidth]{workshop_I/biocro_cartoon.pdf}
\end{center}

\subsection{What we'll be covering today}

\begin{itemize}
  \item The main focus today will be to go through several examples showing how
  to use the most important BioCro functions, culminating with an example of
  parameterizing a model using measured data.

  \item Our goal is to give you an idea of what can be done with the existing
  models available in BioCro, and especially to exhibit tools that can be used
  to gain more understanding.

  \item There are a few things we will not be covering today; these will be
  addressed in future workshops:

  \begin{itemize}
    \item We will not cover the process of adding new model components to
    BioCro. This is not complicated, but some additional software tools are
    required.

    \item Although we will briefly discuss the important processes included in a
    typical BioCro simulation, we will not take detailed look into the rationale
    for these model components, the assumptions underlying them, or the exact
    equations that they use.
  \end{itemize}

  \item Many workshop examples will be based on the Soybean-BioCro model, which
  was originally described in \cite{matthews_soybean_2022}.
\end{itemize}

\newpage

\section{Installing and loading R packages}

For this workshop, we will be using the BioCro R package, the \texttt{lattice}
package (which provides tools for creating plots), the \texttt{dfoptim} package
(which provides tools for optimization), and the \texttt{deSolve} package (which
provides tools for solving differential equations). We will load them now before
moving on to the examples.

\bigskip

\begin{boxCode}
<<eval = FALSE>>=
<<loading_packages>>
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent If you see a warning about the version of BioCro, or if any of the
packages are not available, make sure the latest version of each package is
installed using the following code.

\bigskip

\begin{boxCodeOptional}
<<eval = FALSE>>=
# Make sure packages are installed
install.packages('BioCro')
install.packages('lattice')
install.packages('dfoptim')
install.packages('deSolve')
@
\end{boxCodeOptional}

\newpage

\section{Examining a single module \label{sec_modules}}

\subsection{Getting basic module properties}

\begin{itemize}
  \item In BioCro, equations are grouped into \emph{libraries} of
  \emph{modules}.

  \begin{itemize}
    \item A module represents a set of related equations, while a module library
    contains a set of related modules.

    \item Modules come in two types: \emph{differential} modules calculate time
    derivatives of their outputs, while \emph{direct} modules calculate their
    outputs directly.
  \end{itemize}

  \item For each module, the variables associated with its equations
  can be thought of as its inputs and outputs.

  \begin{itemize}
    \item Example: The C$_3$ assimilation module from the standard module
    library represents the Farquhar-von-Caemmerer-Berry model for C$_3$
    photosynthesis coupled with the Ball-Berry equation for stomatal
    conductance. It needs values of light intensity, leaf temperature, Rubisco
    kinetic parameters, and several other variables. It uses several equations
    to calculate the CO$_2$ assimilation rate, stomatal conductance to H$_2$O,
    and internal CO$_2$ concentration from those inputs.
  \end{itemize}

  \item We can obtain basic information about a module from using the
  \texttt{module\_info} function, which requires a module name as an input.

  \begin{itemize}
    \item In BioCro, modules are identified by \emph{fully-qualified} names that
    include the library name and the local name of the module within the library
    formatted like \texttt{library\_name:local\_name}.

    \item Currently, there is only one official BioCro module library---the
    standard module library---whose name is \texttt{BioCro}.
  \end{itemize}
\end{itemize}

\noindent Here we use \texttt{module\_info} to obtain basic information about a
very simple module from the standard module library.

\bigskip

\begin{boxCode}
<<module_info, eval = FALSE>>=
module_info('BioCro:total_biomass')
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<module_info>>
@
\end{boxOutput}

\begin{boxExercise}
  Type \texttt{?module\_info} in R to access the help page for this function,
  and then try changing the value of \texttt{module\_info}'s optional input
  argument.
\end{boxExercise}

\noindent Note that the \texttt{?} command can be applied to all functions
mentioned in this workshop, and the help pages are a key resource for
understanding how to use each function.

\subsection{Getting a list of all modules}

\begin{itemize}
  \item The standard module library contains many modules.

  \item To see them all, we can use the \texttt{get\_all\_modules} function,
  which requires the name of a module library.

  \item Then, the \texttt{module\_info} function can be used to get basic
  information about any of them.
\end{itemize}

\noindent Here we use \texttt{get\_all\_modules} to view a list of all modules
in the standard module library.

\bigskip

\begin{boxCode}
<<viewing_all_modules, eval = FALSE>>=
print(get_all_modules('BioCro'))
@
\end{boxCode}

\begin{boxOutput}
  The output is too long to reproduce here, but it should be a list of many
  module names, each prefixed by \texttt{BioCro}.
\end{boxOutput}

\begin{boxExercise}
  Pick another module from the list, such as \texttt{BioCro:c3\_assimilation},
  and get its basic information.
\end{boxExercise}

\subsection{Getting more information about a module}

\begin{itemize}
  \item The module information available from within R is missing some important
  parts:

  \begin{itemize}
    \item The units for a module's inputs and outputs.

    \item A description of the module's purpose.

    \item The equations it actually uses.
  \end{itemize}

  \item This information can be found in the source code for each module, which
  is available online at the BioCro
  \href{https://github.com/biocro/biocro}{GitHub repository} or via
  the annotated
  \href{https://biocro.github.io/BioCro-documentation/latest/doxygen/doxygen_docs_modules/namespacestandard_b_m_l.html}{Doxygen documentation}.
  For example:

  \begin{itemize}
    \item A short description of the \texttt{c3\_assimilation} module can be
    found on its associated
    \href{https://biocro.github.io/BioCro-documentation/latest/doxygen/doxygen_docs_modules/classstandard_b_m_l_1_1c3__assimilation.html#details}{class overview page}
    in the Doxygen documentation.

    \item The units for its inputs and outputs can be found as comments in its
    source code, available on its associated
    \href{https://biocro.github.io/BioCro-documentation/latest/doxygen/doxygen_docs_modules/c3__assimilation_8h_source.html}{source code page}
    in the Doxygen documentation (see the comments near \texttt{get\_inputs()}
    and \texttt{get\_outputs()}).

    % The c3_assimilation code is a bit complicated to go through, but we could
    % take a direct look at the total_biomass module.
    \item The code implementation of its equations can also be found in the
    source code (see \texttt{do\_operation()}).
  \end{itemize}

  \item \textbf{Caveat}: Fully documenting the modules is a long and time
  consuming process, so some modules have incomplete or nonexistent
  documentation at the moment.
\end{itemize}

\subsection{Evaluating modules \label{sec_run_module}}

\subsubsection{Evaluating a module once}

\begin{itemize}
  \item Analogous to evaluating an expression of code, we can evaluate a
  module's equations given a set of inputs.

  \item This can be accomplished from \texttt{R} using the
  \texttt{evaluate\_module} function, which requires the name of a module and a
  set of input values. It returns a list of the module's output values.
\end{itemize}

\noindent For example, we can run the \texttt{c3\_assimilation} module using
default soybean values for most of its inputs using the following command, which
also specifies the values of a few module inputs that are not included in the
default soybean values.

% For the next several function examples, we should explicitly describe
% the arguments. Here, module_name and input_quantities. Also, since this is the
% first substantial example, switch to R GUI and show how the documentation for
% evaluate_module can be accessed. Also show how additional info can be found in
% the Practical Guide.

\bigskip

\begin{boxCode}
<<running_a_module, eval = FALSE>>=
evaluate_module(
  'BioCro:c3_assimilation',
  within(soybean$parameters, {
    Qabs = 1800    # absorbed PPFD in micromol / m^2 / s
    StomataWS = 1  # 1 indicates no water stress, 0 indicates maximum water stress
    temp = 25      # air temperature in degrees C
    Tleaf = 27     # leaf temperature in degrees C
    rh = 0.7       # relative humidity (dimensionless)
    gbw = 2.0      # boundary layer conductance to H2O in mol / m^2 / s
  })
)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<running_a_module>>
@
\end{boxOutput}

\begin{boxExercise}
  Try changing some of the input values or running a different module.
\end{boxExercise}

\subsubsection{Calculating and viewing a module response curve \label{sec_response_curve}}

\begin{itemize}
  \item In the previous example, a single value was provided for each of the
  module inputs, so each output also had a single value.

  \item It is also possible to provide a sequence of input values and run the
  module for each of them.

  \item This can be a useful way to see how one of a module's outputs depends on
  one of its inputs; the result from this type of calculation is typically
  called a \emph{response curve}.

  \item This can be done using the \texttt{module\_response\_curve} function,
  which requires us to specify inputs that should remain constant and inputs
  that should be varied.
\end{itemize}

\noindent For example, we can calculate a light response curve using the
\texttt{c3\_assimilation} module.

% Here explain module_name, fixed_quantities, varying_quantities.

\bigskip

\begin{boxCode}
<<c3_light_response_curve>>=
light_response_curve <- module_response_curve(
  'BioCro:c3_assimilation',
  within(soybean$parameters, {
    StomataWS = 1  # 1 indicates no water stress, 0 indicates maximum water stress
    temp = 25      # air temperature in degrees C
    Tleaf = 27     # leaf temperature in degrees C
    rh = 0.7       # relative humidity (dimensionless)
    gbw = 2.0      # boundary layer conductance to H2O in mol / m^2 / s
  }),
  data.frame(Qabs = seq(0, 2000, length.out = 101))
)
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent The return value is a data frame (an R structure equivalent to a
table), and the response of net assimilation to absorbed light intensity can be
plotted from it.

\bigskip

\begin{boxCode}
<<light_response_curve_plot, eval = FALSE>>=
light_response_curve_plot <- xyplot(
  Assim ~ Qabs,
  data = light_response_curve,
  type = 'l',
  grid = TRUE,
  xlab = 'Absorbed PPFD (micromol / m^2 / s)',
  ylab = 'Net assimilation rate\n(micromol / m^2 / s)'
)
print(light_response_curve_plot)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<light_response_curve_plot>>
@
\end{boxOutput}

\noindent The output from \texttt{module\_response\_curve} includes \emph{all}
of the module's outputs, so we could also plot the response of another output
using the same data frame.

\bigskip

\begin{boxExercise}
  Try plotting the response of stomatal conductance (\texttt{Gs}) to light
  intensity.
\end{boxExercise}

\noindent For another example demonstrating how to calculate multiple response
curves at once, see Section \ref{sec_multi_response}.

\newpage

\section{Combining modules to form a larger model \label{sec_simulations}}

\subsection{Running a soybean growth model for one season \label{sec_simulate_one_year}}

\begin{itemize}
  \item A key part of BioCro is the ability to link modules together in chains
  where the output from one module can be used as the input to another.

  \begin{itemize}
    \item Example: the value of the \texttt{StomataWS} input to the
    \texttt{BioCro:c3\_canopy} module could be calculated using the
    \texttt{BioCro:stomata\_water\_stress\_linear} module since
    \texttt{StomataWS} is an output of that module.
  \end{itemize}

  \item This is the main way we can construct complex BioCro models from simpler
  model components.

  \item If a model includes derivative modules, we can solve the resulting set
  of coupled ordinary differential equations to find the model's state at
  specific time points.

  \item The main BioCro function, \texttt{run\_biocro}, does the work of
  combining the modules and integrating the rates of change for us.
\end{itemize}

\noindent For example, we can run a soybean growth model using weather data from
Champaign, Illinois during 2002.

% Here explain the various "equation" parameters and ode_solver, and mention
% that much more information can be found in the Practical Guide.

\bigskip

\begin{boxCode}
<<soybean_simulation>>=
soybean_result <- run_biocro(
  soybean$initial_values,
  soybean$parameters,
  soybean_weather$'2002',
  soybean$direct_modules,
  soybean$differential_modules,
  soybean$ode_solver
)
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent As with \texttt{module\_response\_curve}, the return value from
\texttt{run\_biocro} is a data frame. We can view it directly as a table, or
plot some of its columns against each other. Here we plot the calculated biomass
values against time.

\bigskip

\begin{boxCode}
<<soybean_simulation_plot, eval = FALSE>>=
soybean_biomass_2002_plot <- xyplot(
  Leaf + Stem + Root + Grain ~ fractional_doy,
  data = soybean_result,
  type = 'l',
  grid = TRUE,
  auto.key = list(space = 'right'),
  xlab = 'Day of year (2002)',
  ylab = 'Biomass (Mg / ha)'
)
print(soybean_biomass_2002_plot)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<soybean_simulation_plot>>
@
\end{boxOutput}

\begin{boxExercise}
  Try plotting the soybean biomass against its developmental index (the
  \texttt{DVI} column) instead of time, or try plotting some other outputs like
  leaf area index (the \texttt{lai} column), canopy assimilation rate (the
  \texttt{canopy\_assimilation\_rate} column), or the degree of water stress
  (the \texttt{StomataWS} column).
\end{boxExercise}

\subsection{Components of a typical BioCro crop growth model}

\begin{itemize}
  \item Although the BioCro framework is a general-purpose tool for building and
  solving models, the standard module library is specialized for crop growth
  models that follow a similar organizational structure and contain many similar
  components.

  \item In fact, it is possible to represent most BioCro crop models at a high
  level using a single diagram (subject to some necessary crop-specific
  modifications).
\end{itemize}

\begin{center}
  \includegraphics[width=\textwidth]{workshop_I/generic_model.pdf}
\end{center}

\begin{itemize}
  \item At the code level, each of these important processes is implemented via
  one or more modules.

  \item The particulars may differ from crop to crop; see below for a list of
  all modules in Soybean-BioCro.
\end{itemize}

\bigskip

\begin{boxCode}
<<soybean_modules, eval = FALSE>>=
cat('Direct modules used in the soybean model:\n')
cat(as.character(soybean$direct_modules), sep = '\n')
cat('\nDifferential modules used in the soybean model:\n')
cat(as.character(soybean$differential_modules), sep = '\n')
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<soybean_modules>>
@
\end{boxOutput}

\subsection{Brief overview of the Soybean-BioCro modules}

A full description of Soybean-BioCro, including the assumptions underlying each
component and the rationale for using them, would require at least one textbook
and at least one workshop.

Some of this information can be found in the publication describing the model
(\cite{matthews_soybean_2022}). There are also several textbooks that can be
helpful resources for understanding the many components involved in BioCro's
crop growth simulations
(\cite{campbell_introduction_1998,monteith_principles_2013,thornley_plant_1990}).

Here, we will give a short overview of the major components of Soybean-BioCro,
explaining how the modules relate to the conceptual diagram. Many details about
the module equations have been omitted, but the module code and behavior can be
examined using the methods described previously (Section \ref{sec_modules}).

\begin{itemize}
  \item As the main driver of plant growth, photosynthesis plays a prominent
  role in any BioCro model, and many of the soybean modules are related to
  photosynthesis. Mechanistic models of photosynthesis calculate a carbon
  assimilation rate from inputs like the absorbed light intensity and
  intercellular CO$_2$ concentration, so they can only be applied at scales
  where these inputs are relatively constant---this is typically the leaf scale
  or smaller. So, in a crop growth model, leaf-level photosynthesis equations
  must be embedded in a canopy photosynthesis model where conditions like
  temperature, humidity, and light are allowed to vary within the canopy. In the
  soybean model, conditions in individual layers of the canopy are calculated
  using the \texttt{ten\_layer\_canopy\_properties} module, leaf-level
  assimilation and transpiration rates are calculated for each layer using the
  \texttt{ten\_layer\_c3\_canopy} module, and then the leaf-level rates are
  added across layers by the \texttt{ten\_layer\_canopy\_integrator} module to
  find the canopy-level rates.

  \item Mechanistic photosynthesis models respond to conditions specific to the
  leaf, such as its temperature and intercellular CO$_2$ concentration; however,
  these conditions are generally unknown beforehand since sensor data usually
  only includes properties of the ambient air surrounding the canopy. For this
  reason, it is necessary to include the the processes of heat and gas exchange
  between the leaf and its environment. Gas exchange is regulated by stomatal
  opening, which is typically modeled using empirical relationships; in BioCro,
  we use the Ball-Berry model. Heat exchange (and, ultimately, leaf
  temperature), is determined by conservation of energy; in BioCro, we use
  ``the Penman-Monteith equation'' to calculate leaf temperature, which
  implements energy conservation in an approximate way. These processes are
  included in the \texttt{ten\_layer\_c3\_canopy} module along with
  photosynthesis.

  \item Light levels within the canopy strongly depend on environmental
  conditions outside the canopy, which are supplied via the weather data
  when running a simulation. The soybean model is designed to work with
  weather data sets where the incident sunlight is specified simply as the
  total intensity incident per unit of ground area just above the canopy.
  However, this is not enough information to determine light levels inside
  the canopy---it is critical to know how much of the light is direct vs.
  diffuse radiation, and for the direct light, it is critical to know the
  angle at which it hits the canopy. The
  \texttt{solar\_position\_michalsky} module calculates the angular
  position of the Sun given the latitude, longitude, and time, the \newline
  \texttt{shortwave\_atmospheric\_scattering} module calculates the
  expected fractions of direct vs. diffuse light from the Sun's position,
  and the \texttt{incident\_shortwave\_from\_ground\_par} module calculates
  the actual intensities of direct and diffuse light just above the canopy.

  \item Once a canopy assimilation rate has been calculated, other modules
  decide how the assimilated carbon should be allocated for growth and
  maintenance respiration among the crop's tissues. Currently, BioCro crop
  models all use \emph{partitioning} models, where fractions of the assimilated
  carbon are assigned to each tissue to be used for growth and respiration; this
  is accomplished by pairing the \texttt{partitioning\_growth} module with one
  of the available ``partitioning growth calculator'' modules, which each
  implement slightly different rules for taking respiration and other factors
  into account. The soybean model uses the \newline
  \texttt{partitioning\_growth\_calculator} module as its partitioning growth
  calculator.

  \item There are also several possible strategies for choosing the
  ``partitioning coefficients,'' dimensionless fractions that determine the
  relative amounts of carbon devoted to each tissue in a partitioning growth
  model. In general, these coefficients depend on the developmental stage of the
  plant; as an extreme example, soybeans do not devote any carbon towards pod
  production until the flowering stage has been reached. The soybean model uses
  the \texttt{partitioning\_coefficient\_logistic} module to vary these
  coefficients continuously as the crop ages. The developmental stage of the
  crop is expressed as a dimensionless \emph{development index} (DVI), which is
  determined from the temperature and photoperiod using the \newline
  \texttt{soybean\_development\_rate\_calculator} module. Most BioCro modules
  are intended to be applicable to multiple crops, but the developmental
  response to temperature and photoperiod is very specific to soybean.

  \item As a crop continues to age, it eventually begins to senesce. The soybean
  model uses the \newline \texttt{senescence\_logistic} module to accomplish
  this, which decreases the mass of each tissue at a rate proportional to its
  mass; in other words, it implements an exponential decay. Some of the lost
  mass is converted to litter, and some is remobilized for use by other organs
  such as the pod. The rate constants for senescence are calculated from soybean
  DVI by the \texttt{senescence\_coefficient\_logistic} module.

  \item Water availability plays a major role in crop growth. When water is
  scarce, plants respond by closing their stomata to reduce transpiration, which
  also reduces carbon assimilation. In the soybean model, this relationship is
  implemented by the \texttt{stomata\_water\_stress\_linear} module, which
  determines a reduction factor for stomatal conductance from the soil water
  content. In turn, the soil water content is influenced by several factors:
  rainfall is the only source of soil water, while water available to the plant
  is lost due to canopy transpiration, evaporation from the soil surface,
  runoff, and the flow of water away from the surface to deeper soil layers.
  These processes are included in the soybean model via the
  \texttt{soil\_evaporation} and \texttt{two\_layer\_soil\_profile} modules.

  \item The \texttt{parameter\_calculator} module is used to determine the
  canopy's leaf area index from the total leaf mass.

  \item The \texttt{thermal\_time\_linear} module is included for historical
  reasons and its output is not actually used by any other component of the
  model; it could be removed without any effect on the simulated values of
  biomass.
\end{itemize}

\newpage

\section{More analysis techniques}

\subsection{Optimization problems}

\begin{itemize}
  \item We've now seen the essential BioCro functions, but have only just
  scratched the surface of what we can do with them.

  \item R offers many possibilities in addition to the plotting tools that we
  have already used.

  \item For example, we can solve optimization problems with functions like
  \texttt{optim}.

  \begin{itemize}
    \item The \texttt{optim} function is a general-purpose optimizer that
    minimizes the return value of another function (\texttt{fn}).

    \item Most optimizers, including \texttt{optim}, require that \texttt{fn}
    takes a numeric vector as an input and returns a single numeric value as its
    output.
  \end{itemize}

  \item We could use this to maximize an output like assimilation or to fit
  simulated biomass to measured data.

  \item But, first we need to create a suitable \texttt{fn} from the other
  BioCro functions like \texttt{evaluate\_module} and \texttt{run\_biocro}.
  These functions have too many inputs and outputs, so they need to be modified.

  \item As a general strategy, we can take the following two steps to create a
  suitable \texttt{fn}:

  \begin{itemize}
    \item Identify inputs that we want to vary, and fix the values of all other
    inputs; this technique is known in computer programming as \emph{partial
    application}.

    \item Choose a method for extracting one important value to be optimized;
    this step is more open-ended and will depend on the particular situation.
  \end{itemize}

  \item The BioCro package provides functions to help with partial application
  (\texttt{partial\_evaluate\_module} and \texttt{partial\_run\_biocro}), and
  the following examples will demonstrate how they can be used in the context of
  optimization.
\end{itemize}

\subsection{Maximizing soybean assimilation \label{sec_optimize_module}}

\begin{itemize}
  \item Let's say we want to maximize soybean assimilation rate by varying the
  leaf temperature; in other words, we want to find the temperature that
  produces the highest soybean assimilation rate for a set of otherwise fixed
  conditions.

  \item In this case, we could use \texttt{optim} to maximize the value of a
  function \texttt{fn} that takes a value of leaf temperature as an input and
  returns a value of the net assimilation rate.
\end{itemize}

\noindent Here we show how to generate a suitable function from the
\texttt{BioCro:c3\_assimilation} module. The first step is to indentify leaf
temperature as an independent input and fix the other module input values.

\bigskip

\begin{boxCode}
<<partial_evaluate_module_p1, eval = FALSE>>=
c3_tleaf <- partial_evaluate_module(
  'BioCro:c3_assimilation',
  within(soybean$parameters, {
    Qabs = 1800    # absorbed PPFD in micromol / m^2 / s
    StomataWS = 1  # 1 indicates no water stress, 0 indicates maximum water stress
    temp = 25      # air temperature in degrees C
    rh = 0.7       # relative humidity (dimensionless)
    gbw = 2.0      # boundary layer conductance to H2O in mol / m^2 / s
  }),
  'Tleaf'          # specify the inputs that should not be fixed
)

# We can run the module using a leaf temperature of 27 degrees C
str(c3_tleaf(27))
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<partial_evaluate_module_p1>>
@
\end{boxOutput}

\noindent The new \texttt{c3\_tleaf} function accepts the required input, but it
returns much more information than we need. Here we create a simple ``wrapper''
for this function that extracts only the net assimilation output.

\bigskip

\begin{boxCode}
<<partial_evaluate_module_p2, eval = FALSE>>=
c3_assim_from_tleaf <- function(x) {c3_tleaf(x)$outputs$Assim}

# We can run the module using a leaf temperature of 27 degrees C, only returning
# the Assim output
c3_assim_from_tleaf(27)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<partial_evaluate_module_p2>>
@
\end{boxOutput}

\noindent Now we can pass this function to \texttt{optim}, with one small
modification: \texttt{optim} actually \emph{minimizes} the value of the function
passed to it, so if we want to \emph{maximize} net assimilation, we need to
rephrase the problem as minimizing the negative of the value of net
assimilation.

\bigskip

\begin{boxCode}
<<finding_optimal_temperature, eval = FALSE>>=
optim_result <- optim(
  25,                                    # initial guess for optimal temperature
  function(x) {-c3_assim_from_tleaf(x)}, # rephrase to a minimization
  method = 'Brent',                      # works well for 1D optimization
  lower = 0,                             # lower limit of temperatures to try
  upper = 50                             # upper limit of temperatures to try
)

# Print the optimal Tleaf value
optim_result$par
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<finding_optimal_temperature>>
@
\end{boxOutput}

\noindent For a more advanced example where net assimilation is maximized under
multiple conditions to calculate an optimal temperature curve, see Section
\ref{sec_advanced_maximization}.

\subsection{Parameterizing a model using measured data \label{sec_optimize_simulation}}

\begin{itemize}
  \item One of the most important parts of developing a model is parameterizing
  it by comparing its predictions against measured data.

  \item An optimizer can be used to accomplish this goal by finding the optimal
  values of parameters that produce the best agreement with the measurements.

  \item In order to do this, the main tasks are to:

  \begin{itemize}
    \item Obtain measurements of quantities that can be predicted by the model.

    \item Identify which of the model parameters should be varied to create the
    best match with the measured data.

    \item Define an \emph{error metric} that quantifies the degree of agreement
    between the predictions and the observations; typically this will be
    something like the $\chi^2$ statistic. Smaller values of the error metric
    should indicate a closer agreement.

    \item Create a function that accepts a single vector (the values of the
    selected parameters) and returns a single number (the resulting value of the
    error metric).
  \end{itemize}

  \item Once these tasks have been performed, the resulting function can then be
  passed to an optimizer, which will find the values that minimize the error.

  \item Here we show how this parameterization can be accomplished using BioCro.
  In this example:

  \begin{itemize}
    \item We have a basic model for Miscanthus growth.

    \item We have Miscanthus leaf area index (LAI) observed at multiple times
    during the season and above-ground dry yield at the end of the season.

    \item Many parameters affect both of these values, but we will fit only the
    initial specific leaf area (\texttt{iSp}) and the ``specific leaf area
    thermal time decay'' (\texttt{Sp\_thermal\_time\_decay}), which reduces the
    specific leaf area as the crop ages.

    \item We will use $\chi^2$ for the error metric; this is a useful statistic
    when fitting observations of quantities that may have very different
    magnitudes due to differences in units.

    \item We will use one of the derivative-free optimization algorithms
    available from the \texttt{dfoptim} package, since it tends to converge
    quickly in these applications.
  \end{itemize}
\end{itemize}

\noindent The basic Miscanthus model is included with the BioCro R package, as
is the weather data. The observed values of LAI and above-ground dry yield will
be defined below using R commands. In a more realistic situation, the model
definition, weather data, and observations may be stored in text or CSV files
and subsequently loaded into the R workspace.

\bigskip

\begin{boxCode}
<<load_miscanthus_data, eval = FALSE>>=
# Here we create a data frame with the Miscanthus observations.
# - time: The time of the observation following BioCro conventions, expressed as
#   the number of hours since the start of the year
# - lai: The leaf area index (dimensionless)
# - above_ground_dry_yield: Total stem and leaf mass in Mg / ha
yield <- utils::read.table(
  textConnection('
    time lai    above_ground_dry_yield
    4224     0.0445 NA
    4296     0.0035 NA
    4416     0.0104 NA
    4536     0.0568 NA
    4608     0.0878 NA
    4704     0.2725 NA
    4824     2.1064 NA
    4896     2.7614 NA
    4992     3.899  NA
    5064     3.4318 NA
    5160     4.4921 NA
    5232     4.8522 NA
    5304     5.1393 NA
    5400     4.9133 NA
    5472     4.7485 NA
    6120     NA     19.35101369
  '),
  header = TRUE
)

# View the result
str(yield)

# Now we create a corresponding weather data set
min_doy <- min(floor(yield$time / 24)) - 1
max_doy <- max(ceiling(yield$time / 24)) + 1

miscanthus_weather <- weather[['2016']]

miscanthus_weather <-
  with(miscanthus_weather, {miscanthus_weather[doy >= min_doy & doy <= max_doy, ]})
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<load_miscanthus_data>>
@
\end{boxOutput}

\noindent Next, we'll create a function that runs a miscanthus growth simulation
using the weather data but accepts only \texttt{iSp} and
\texttt{Sp\_thermal\_time\_decay} as inputs; this can be accomplished using
\texttt{partial\_run\_biocro}. When comparing to the measured data, we'll need
the above-ground dry yield; this isn't included in the typical simulation
output, but can be calculated afterwards.

\bigskip

\begin{boxCode}
<<miscanthus_partial_function>>=
par_to_optimize <- c('iSp', 'Sp_thermal_time_decay')

partial_function <- function(x) {
  f = with(miscanthus_x_giganteus, {partial_run_biocro(
    initial_values,
    parameters,
    miscanthus_weather,
    direct_modules,
    differential_modules,
    ode_solver,
    par_to_optimize
  )})
  r = f(x)
  r = within(r, {above_ground_dry_yield = Leaf + Stem})
  r
}
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent Now \texttt{partial\_function} accepts a vector of the two values, but
it still returns all of the model output rather than a single value to minimize.
We can use it to calculate $\chi^2$ by wrapping another function around it.

\bigskip

\begin{boxCode}
<<miscanthus_minimization_function, eval = FALSE>>=
to_minimize <- function(x) {
  # Get results from the model and then pull out times at which there are
  # observed data. Use tryCatch to ensure that bad parameters do not completely
  # prevent the optimization from running.
  r <- tryCatch(
    {partial_function(x)},
    error = function(e) {data.frame()}
  )
  r_at_obs <- r[r$time %in% yield$time, ]

  # We'll used the chi-squared statistic. It is the sum of squared differences
  # divided by predicted values. Using this gives more equal weight to each
  # variable you're predicting. Otherwise, values that are big because of unit
  # differences will have more weight.
  obs_lai <- yield$lai
  pred_lai <- r_at_obs$lai
  ss1 <- sum(((obs_lai - pred_lai)^2 / pred_lai), na.rm = TRUE)

  obs_yield <- yield$above_ground_dry_yield
  pred_yield <- r_at_obs$above_ground_dry_yield
  ss2 <- sum(((obs_yield - pred_yield)^2 / pred_yield), na.rm = TRUE)
  ss <- ss1 + ss2

  # Some parameters cause the model to fail completely. Add a large penalty in
  # these cases. This will make the optimizer move away from unrealistic input
  # values. Here, `!is.finite` will find Inf, NaN, and NA values.
  if (nrow(r) < 1) {
    ss <- ss + 1000
  }
  ss
}

# Test the function with default values
print(to_minimize(unlist(miscanthus_x_giganteus$parameters[par_to_optimize])))
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<miscanthus_minimization_function>>
@
\end{boxOutput}

\noindent Now we can perform the optimization; we'll also wrap the call to the
optimizer in \texttt{system.time} so we can see how long it takes to run.

\bigskip

\begin{boxCode}
<<miscanthus_optimization, eval = FALSE>>=
system.time({
  miscanthus_optim_result <- nmkb(
    par = unlist(miscanthus_x_giganteus$parameters[par_to_optimize]),
    fn = to_minimize,
    lower = c(1e-3, -0.1),
    upper = c(10, 0.1)
  )
})

# See the original and optimized parameter values
cat('Original values:\n')
print(miscanthus_x_giganteus$parameters[par_to_optimize])
cat('Optimized values:\n')
print(setNames(miscanthus_optim_result$par, par_to_optimize))
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<miscanthus_optimization>>
@
\end{boxOutput}

\noindent Now we can check the result. In these plots, simulated values are
shown as lines and observed values are shown as solid circles.

\bigskip

\begin{boxCode}
<<miscanthus_optimizer_check, eval = FALSE>>=
original_res <- partial_function(miscanthus_x_giganteus$parameters[par_to_optimize])
optimized_res <- partial_function(miscanthus_optim_result$par)

full_res <- rbind(
  within(original_res, {par_type = 'Original parameters'}),
  within(optimized_res, {par_type = 'Optimized parameters'})
)

xyplot(
  lai ~ time,
  group = par_type,
  data = full_res,
  type = 'l',
  xlab = 'BioCro Time',
  ylab = 'Leaf area index (dimensionless)',
  par.settings = list(superpose.line = list(lty = c(1, 2))),
  auto.key = list(space = 'top'),
  panel = function(...) {
    panel.xyplot(...)
    panel.points(yield$lai ~ yield$time, pch = 16, col = 'black')
  }
)

xyplot(
  above_ground_dry_yield ~ time,
  group = par_type,
  data = full_res,
  type = 'l',
  xlab = 'BioCro Time',
  ylab = 'Above-ground dry yield (Mg / ha)',
  par.settings = list(superpose.line = list(lty = c(1, 2))),
  auto.key = list(space = 'top'),
  panel = function(...) {
    panel.xyplot(...)
    panel.points(yield$above_ground_dry_yield ~ yield$time, pch = 16, col = 'black')
  }
)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<miscanthus_optimizer_check>>
@
\end{boxOutput}

\noindent This optimization may seem complicated, but it is actually much
simpler than a realistic model parameterization, which may include many more
observations and parameters. A more reliable and useful objective function would
also include more checks for error conditions.

A full example demonstrating one approach to parameterizing BioCro's soybean
model can be found online at the documentation web site for the
\texttt{BioCroValidation} R package:
\url{https://biocro.org/BioCroValidation/articles/parameterizing_soybean_biocro.html}.

\subsection{What comes next}

\textbf{That's the end of the structured part of the workshop!} With any
remaining time that might be left, you can:
\begin{itemize}
  \item Participate in the soybean challenge (Section \ref{sec_challenge}).

  \item Try out some of the additional examples (Section
  \ref{sec_additional_examples}).

  \item Try working on your own modeling ideas.

  \item Ask any other questions you might have.

  \item Learn more about BioCro's approach to modular modeling (Section
  \ref{sec_modular}).

  \item Read one of the articles on the BioCro web site
  (\url{https://biocro.org})
\end{itemize}

\newpage

\section{The soybean challenge \label{sec_challenge}}

One way to test your BioCro knowledge is to try to maximize soybean yield. As in
Section \ref{sec_simulate_one_year}, we can run a soybean simulation for 2002.

\bigskip

\begin{boxCode}
<<eval = FALSE>>=
<<soybean_simulation>>
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent Then, the final pod biomass can be extracted.

\bigskip

\begin{boxCode}
<<soybean_final_yield, eval = FALSE>>=
soybean_result$Grain[nrow(soybean_result)]
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<soybean_final_yield>>
@
\end{boxOutput}

\begin{boxExercise}
  Your task is to increase that value!
\end{boxExercise}

\noindent For example, you could try increasing a photosynthesis parameter like
$V_{c,max}$, which is represented in the soybean model as
\texttt{Vcmax\_at\_25}.

\bigskip

\begin{boxCode}
<<soybean_vmax, eval = FALSE>>=
soybean_result_new <- run_biocro(
  soybean$initial_values,
  within(soybean$parameters, {Vcmax_at_25 = 200}),
  soybean_weather$'2002',
  soybean$direct_modules,
  soybean$differential_modules,
  soybean$ode_solver
)

soybean_result_new$Grain[nrow(soybean_result)]
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<soybean_vmax>>
@
\end{boxOutput}

\noindent Any approach is allowed! If you think you have a way to get a super
high yield and would like to share it, email your code to
\href{mailto:eloch@illinois.edu}{eloch@illinois.edu} and
\href{mailto:jmcgrath@illinois.edu}{jmcgrath@illinois.edu}. Interesting
approaches will be showcased on the BioCro website (with your permission).

\newpage

\section{Additional examples \label{sec_additional_examples}}

\subsection{Swapping a model component}

In Section \ref{sec_simulate_one_year}, we ran a default Soybean-BioCro
simulation for weather data from 2002.

\bigskip

\begin{boxCode}
<<eval = FALSE>>=
<<soybean_simulation>>
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent In this simulation, photosynthesis was included via the mechanistic
Farquhar-von-Caemmerer-Berry (FvCB) model. Alternatively, it would be possible
to use a simpler photosynthesis model based on radiation use efficiency (RUE).
In the RUE model, the gross assimilation rate is directly proportional to the
incident light intensity. The standard BioCro module library contains a RUE
canopy photosynthesis module, so it is simple to run an alternate soybean
simulation using RUE photosynthesis in place of the FvCB model. In addition to
switching a module, we will also need to provide a value for the efficiency,
which is called \texttt{alpha\_rue}.

\bigskip

\begin{boxCode}
<<soybean_simulation_rue>>=
soybean_result_rue <- run_biocro(
  soybean$initial_values,
  within(soybean$parameters, {alpha_rue = 0.05}),
  soybean_weather$'2002',
  within(soybean$direct_modules, {
    canopy_photosynthesis = 'BioCro:ten_layer_rue_canopy'
  }),
  soybean$differential_modules,
  soybean$ode_solver
)
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

\noindent Predicted biomass values from the two versions can be compared
visually:

\bigskip

\begin{boxCode}
<<soybean_simulation_comparison, eval = FALSE>>=
biomass_col <- c('fractional_doy', 'Leaf', 'Stem', 'Root', 'Grain')
soybean_comp <- rbind(
  within(soybean_result[biomass_col], {photo_method = 'FvCB'}),
  within(soybean_result_rue[biomass_col], {photo_method = 'RUE'})
)

xyplot(
  Leaf + Stem + Root + Grain ~ fractional_doy,
  group = photo_method,
  data = soybean_comp,
  type = 'l',
  auto.key = list(space = 'right'),
  grid = TRUE,
  xlab = 'Day of year (2002)',
  ylab = 'Biomass (Mg / ha)'
)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<soybean_simulation_comparison>>
@
\end{boxOutput}

\noindent With this value of \texttt{alpha\_rue}, the agreement between the
model predictions is not so great. However, an optimization procedure similar to
the ones in Section \ref{sec_optimize_simulation} could be used to find the
value of \texttt{alpha\_rue} that produces the best agreement. Afterwards, the
response of the two different soybean models to important factors like
temperature and CO$_2$ can be compared using response curves (as in Section
\ref{sec_response_curve}) and sensitivity analysis (as in Sections
\ref{sec_module_sensitivity} and \ref{sec_module_sensitivity}). This type of
analysis can reveal scenarios where the model behavior is expected to differ.
For an example of how this could be done, see \cite{lochocki_biocro_2022} and
the \emph{Quantitative Comparison Between Two Photosynthesis Models} article.

\subsection{Simultaneously calculating and plotting multiple response curves \label{sec_multi_response}}

When calling \texttt{module\_response\_curve}, it is possible to vary multiple
inputs at one time, which allows us to calculate multiple response curves with
one command.

For example, we can calculate the temperature response of light-saturated net
assimilation at several values of relative humidity (RH). Here, the leaf
temperature and humidity values are independent of each other, so we use the
\texttt{expand.grid} function to form a data frame of all possible combinations
of their values. Then, we use the \texttt{group} option in \texttt{xyplot} to
separately plot the light response curves for each value of relative humidity.
We also use the \texttt{paste} function to generate an informative plot title
from the information contained in the response curve data frame.

\bigskip

\begin{boxCode}
<<multiple_response_curves, eval = FALSE>>=
temperature_response_curve <- module_response_curve(
  'BioCro:c3_assimilation',
  within(soybean$parameters, {Qabs = 2000; StomataWS = 1; temp = 25; gbw = 2.0}),
  expand.grid(
    Tleaf = seq(from = 0, to = 40, length.out = 101),
    rh = c(0.2, 0.5, 0.8)
  )
)

caption <- paste(
  'Response curves calculated with several RH\nvalues and Q =',
  unique(temperature_response_curve$Qabs),
  'micromol / m^2 / s\nusing the',
  unique(temperature_response_curve$module_name),
  'module'
)

temperature_response_curve_plot <- xyplot(
  Assim ~ Tleaf,
  group = rh,
  data = temperature_response_curve,
  auto.key = list(space = 'right'),
  type = 'l',
  xlab = 'Leaf temperature (degrees C)',
  ylab = 'Net assimilation rate\n(micromol / m^2 / s)',
  main = caption
)
print(temperature_response_curve_plot)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<multiple_response_curves>>
@
\end{boxOutput}

\begin{boxExercise}
  Try changing the value of the absorbed photosynthetically active photon flux
  density \texttt{Qabs} and notice how the plot caption is automatically updated
  to reflect the new value.
\end{boxExercise}

\subsection{Maximizing net assimilation under multiple conditions \label{sec_advanced_maximization}}

An interesting feature of the response curves in Section
\ref{sec_multi_response} is that for each value of RH, there is an optimal value
of leaf temperature that maximizes the net assimilation rate. We can use a
combination of BioCro tools and built-in R tools to determine the optimal
temperature for a given RH value. In this example, we use the
\texttt{partial\_evaluate\_module} BioCro function to hold all module inputs
except \texttt{Tleaf} and \texttt{RH} constant. Then we ask an optimizer to find
the value of \texttt{Tleaf} that maximizes the module's net assimilation output
for a sequence of humidities. Using this process, we generate a curve we can use
to visualize how the optimal temperature for C$_3$ photosynthesis depends on
ambient humidity, according to this model.

\bigskip

\begin{boxCode}
<<more_advanced_module_optimization, eval = FALSE>>=
c3_tleaf_rh <- partial_evaluate_module(
  'BioCro:c3_assimilation',
  within(soybean$parameters, {Qabs = 2000; StomataWS = 1; temp = 25; gbw = 2.0}),
  c('Tleaf', 'rh')
)

rh_seq <- seq(0.2, 1, length.out = 21)

optim_temp <- sapply(rh_seq, function(rh) {
  optim_result_rh <- optim(
    25,
    function(tl) {-c3_tleaf_rh(c(tl, rh))$outputs$Assim},
    method = 'Brent',
    lower = 0,
    upper = 50
  )
  optim_result_rh$par
})

optim_temp_plot <- xyplot(
  optim_temp ~ rh_seq,
  type = 'b',
  pch = 20,
  xlab = 'Relative humidity (dimensionless)',
  ylab = 'Optimal leaf temperature for\nmaximum C3 assimilation\n(degrees C)',
  main = 'Optimizing C3 photosynthesis when\nQabs = 2000 in the absence of water stress'
)
print(optim_temp_plot)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<more_advanced_module_optimization>>
@
\end{boxOutput}

\noindent It is well-known that the optimal temperature for photosynthesis
depends on the ambient CO$_2$ concentration (\cite{long_modification_1991}).
This example shows that the optimal temperature also changes with humidity
levels, shifting to lower temperatures in drier conditions.

\bigskip

\begin{boxExercise}
  Try finding the optimal LAI that maximizes net soybean canopy assimilation for
  fixed environmental conditions. For this, the \texttt{BioCro:c3\_canopy}
  module would be required instead of the \texttt{BioCro:c3\_assimilation}
  module.
\end{boxExercise}

\subsection{Calculating module sensitivity coefficients \label{sec_module_sensitivity}}

\emph{Sensitivity analysis} can be a powerful way to understand and demonstrate
the behavior of a model component or a model as a whole. Essentially, we choose
a particular output that we're interested in (such as net assimilation rate) and
calculate changes in that variable that occur in response to small changes in
an input. This technique can reveal which model inputs have the biggest impact
on its important outputs; in turn, this knowledge can be used to guide future
investigations.

There are several ways to calculate sensitivity coefficients during
sensitivity analysis. Let's say we have a function $f(x)$ that calculates a
value of $y$ from a value of $x$, and we want to calculate the sensitivity of
$y$ to $x$ at a value of $x_0$. The simplest option would be to choose a small
$x$ step size ($\delta x$) and compute the sensitivity as
\begin{equation}
s_1 = f(x_0 + \delta x) - f(x_0).
\end{equation}
In other words, $s_1$ is the change in $y$ caused by an increase in $x$ from
$x_0$ to $x_0 + \delta x$. A disadvantage of this approach is that $s_1$
strongly depends on the value of $\delta x$. So we could also try
\begin{equation}
s_2 = s_1 / \delta x.
\end{equation}
Now we can interpret $s_2$ as the change in $y$ per change in $x$. Note that as
$\delta x$ approaches 0, $s_2$ approaches the derivative $df / dx$ evaluated at
$x_0$. In other words, for values of $\delta x$ that are sufficiently small,
$s_2$ is independent of $\delta x$. Another option is to calculate fractional
changes rather than absolute changes, i.e.,
\begin{equation}
s_3 = \frac{s_1 / f(x_0)}{\delta x / x_0}
    = \frac{s_2}{f(x_0) / x_0}
    = s_2 \frac{x_0}{f(x_0)}.
\end{equation}
We can interpret $s_3$ as the relative change in $y$ per relative change in $x$.
As $\delta x$ approaches 0, $s_3$ approaches $(df / dx) (x_0 / f(x_0))$, where
the derivative is evaluated at $x_0$. Again, for values of $\delta x$ that are
sufficiently small, $s_3$ is independent of $\delta x$. Note that this approach
is not viable if $x_0$ is zero because $s_3$ is undefined in that case. (If $df
/ dx$ approaches infinity as $x_0$ approaches 0, then $s_3$ may have a finite
value that could be calculated using L'H\^{o}pital's rule; however, this
situation is difficult to deal with using numerical methods.)

Also note that there are two strategies commonly employed for choosing
$\delta x$. One is to simply specify an absolute value. The other is to specify
a relative step size where $\delta x = \epsilon x_0$ for a small value of
$\epsilon$.

Here we define a sensitivity helping function that requires $f(x)$, $x_0$, and
either $\delta x$ or $\epsilon$ as input arguments, and returns the values of
$s_1$, $s_2$, and $s_3$ as a data frame. If \texttt{delta\_x} is \texttt{NULL},
then a relative step based on $\epsilon$ will be used for the calculations.

\bigskip

\begin{boxCode}
<<sensitivity_function>>=
sensitivity <- function(FUN, x0, ep = 1e-6, delta_x = NULL) {
  if (is.null(delta_x)) {
    delta_x <- x0 * ep
  }

  x1 <- x0 + delta_x
  y0 <- FUN(x0)
  y1 <- FUN(x1)
  s1 <- y1 - y0
  s2 <- s1 / delta_x
  s3 <- s2 / (y0 / x0)

  return(data.frame(
    x0 = x0,
    x1 = x1,
    y0 = y0,
    y1 = y1,
    s1 = s1,
    s2 = s2,
    s3 = s3
  ))
}
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

Now, let's calculate sensitivity coefficients for the \texttt{c3\_assimilation}
module, treating the ambient CO$_2$ concentration $C_a$ as the independent
variable and the net assimilation as the dependent variable. We'll also provide
an option to specify the absorbed light level. First, we'll need to create a
function $f$ such that $f$(CO$_2$, Q) = net assimilation. We can specify the
independent variables using \texttt{partial\_evaluate\_module}, and then create
another function wrapper later that selects just the net assimilation output.

\bigskip

\begin{boxCode}
<<sensitivity_co2_function>>=
co2_func <- partial_evaluate_module(
  'BioCro:c3_assimilation',
  within(soybean$parameters, {
    StomataWS = 1
    temp = 25
    Tleaf = 27
    rh = 0.7
    gbw = 2.0
  }),
  c('Catm', 'Qabs')
)
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

Now we will define a range of absorbed light values to use and calculate the
sensitivity coefficients for each one using a base level of $C_a$ = 400 ppm.

\bigskip

\begin{boxCode}
<<sensitivity_calculations>>=
qabs_seq <- seq(0, 2000, length.out = 101)

sens_result <- do.call(rbind, lapply(qabs_seq, function(Qabs) {
  sens <- sensitivity(
    function(catm) {co2_func(c(catm, Qabs))$outputs$Assim},
    400
  )
  sens$Qabs <- Qabs  # Also include the absorbed light level in the result
  return(sens)
}))
@
\end{boxCode}

\begin{boxOutput}
  \nooutput
\end{boxOutput}

Now we can see the sensitivity of net assimilation to ambient CO$_2$
concentration at different levels of absorbed light intensity.

\bigskip

\begin{boxCode}
<<sensitivity_plot, eval = FALSE>>=
sensitivity_plot <- xyplot(
  s2 ~ Qabs,
  data = sens_result,
  type = 'l',
  grid = TRUE,
  xlab = 'absorbed PPFD (micromol / m^2 / s)',
  ylab = 'dA / dCa (dimensionless)'
)
print(sensitivity_plot)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<sensitivity_plot>>
@
\end{boxOutput}

From this plot, we can learn several things. One observation is that the
sensitivity coefficient is non-negative for all values of absorbed light; this
indicates additional CO$_2$ never causes a decrease in soybean assimilation.
Another observation is that that soybean assimilation is most sensitive to
increases in ambient CO$_2$ levels when the absorbed light levels are high. This
agrees with our intuition; CO$_2$ assimilation is limited by light availability
at low light levels, so additional CO$_2$ cannot be used for assimilation.

\bigskip

\begin{boxExercise}
  Use the \texttt{BioCro:c4\_assimilation} module to calculate a similar
  sensitivity curve for miscanthus (using default values from
  \texttt{miscanthus\_x\_giganteus\_parameters}).
\end{boxExercise}

\noindent This will reveal some differences between the response of C$_3$ and
C$_4$ photosynthesis to changes in atmospheric CO$_2$ levels.

\subsection{Calculating simulation sensitivity coefficients \label{sec_sim_sensitivity}}

It is possible to calculate the sensitivity of simulation outputs like final
pod biomass to input parameters like $C_a$ following the same approach used in
Section \ref{sec_module_sensitivity}. The only difference would be that
\texttt{partial\_run\_biocro} will be used to construct $f(x)$, rather than
\texttt{partial\_evaluate\_module}.

As a simple example, we will calculate the sensitivity of final pod biomass in
2002 to the value of \texttt{alphaLeaf}. Here we will use partial application,
and will extract just the final seed mass from a full simulation result, similar
to the strategy used in Section \ref{sec_optimize_module}. These techniques will
create a function that can be passed to the sensitivity calculator defined in
Section \ref{sec_module_sensitivity}.

\bigskip

\begin{boxCode}
<<simulation_sensitivity, eval = FALSE>>=
# Use partial application to fix all inputs except alphaLeaf
aleaf_func <- with(soybean, {partial_run_biocro(
  initial_values,
  parameters,
  soybean_weather$'2002',
  direct_modules,
  differential_modules,
  ode_solver,
  'alphaLeaf'
)})

# Helper function that returns just the final seed mass
final_pod_func <- function(alphaLeaf) {
  sim_result <- aleaf_func(alphaLeaf)
  sim_result$Grain[nrow(sim_result)]
}

# Calculate sensitivity
sensitivity(final_pod_func, soybean$parameters$alphaLeaf)
@
\end{boxCode}

\begin{boxOutput}
<<echo = FALSE>>=
<<simulation_sensitivity>>
@
\end{boxOutput}

An interesting observation here is that the sensitivity coefficients are
negative, indicating that increases in \texttt{alphaLeaf} cause decreases in
yield. \texttt{alphaLeaf} controls the crop's level of leaf investment, so we
have learned that additional leaf investment is detrimental to soybean yield;
this agrees with previous results indicating that soybean canopies are larger
than necessary for optimal yields (\cite{srinivasan_decreasing_2017}).

\bigskip

\begin{boxExercise}
  Try calculating the sensitivity coefficient for the response of soybean yield
  to changes in atmospheric CO$_2$ concentration.
\end{boxExercise}

\noindent See \cite{lochocki_biocro_2022} for a more detailed example of
calculating and using simulation sensitivity coefficients.

\newpage

\section{Understanding BioCro's approach to modular modeling \label{sec_modular}}

\subsection{Three levels of computational modeling}

In general, there are several different ways to think about a computational
model as we move from abstract to concrete representations. Defining a model
using computer code---the most concrete representation---is necessary for
numerically solving it, but there are several complications associated with
modeling at the code level. BioCro is designed to help mitigate these issues.
So, to better understand BioCro, it is helpful to understand the three
essential ways to think about a model: at the conceptual level, at the equation
level, and at the code level. In this section, we will illustrate these levels
using a very simple plant growth model.

\subsubsection{The concept level \label{sec_concept_level}}

At the conceptual level, we often represent models using diagrams like the one
in Figure \ref{fig_conceptual_model}, where the model is shown as a collection
of major components (boxes) and the connections between them (arrows). This
particular diagram shows that the model can be divided into two conceptually
distinct parts: leaf photosynthesis and carbon partitioning. The
photosynthesis component uses the absorbed sunlight level and the leaf mass to
determine the overall rate of mass gain due to carbon assimilation, and the
partitioning component determines the separate rates of root and leaf mass gain
from the overall rate. This type of diagram is essential when building a model
because it allows us to identify the important processes, inputs, and outputs
that we want to include in the model, as well as the relationships between them.
However, it doesn't let us actually make quantitative calculations or
predictions.

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[width=0.4\textwidth]{workshop_I/conceptual_model.pdf}
    \caption{
      A conceptual flow diagram of a simple plant growth model where the
      absorbed sunlight and total leaf mass are used to determine the rate of
      carbon assimilation, and then the assimilated carbon is partitioned into
      leaf and root compartments where it determines the rates of mass gain.
      This is an informal style of diagram, but more specialized ones called
      \emph{Forrester diagrams} more clearly specify different types of model
      components.
    }
    \label{fig_conceptual_model}
  \end{center}
\end{figure}

\subsubsection{The equation level \label{sec_equation_level}}

In order to make calculations, we first need to associate equations with the
boxes and lines in the conceptual diagram. Typically there are multiple
possibilities for the equations to use; our choices will depend on the
information we have available to us, as well as our goals for how we want to use
the model. Here we will use some simple equations to represent the model.

For photosynthesis, we will calculate the rate of carbon assimilation per unit
leaf area ($A$; mol m$^{-2}$ s$^{-1}$) and the overall rate of mass gain ($G$;
kg s$^{-1}$) from the absorbed photosynthetically-active photon flux density
($Q$; mol m$^{-2}$ s$^{-1}$) as follows:
%
\begin{subequations}
  \label{eq:photo}
  \begin{align}
    A  & = Q \cdot \alpha_{RUE} \\[5pt]
    G & = A \cdot M_{leaf} \cdot SLA \cdot C_{conversion}
  \end{align}
\end{subequations}
%
Here, $\alpha_{RUE}$ (mol CO$_2$ (mol photon)$^{-1}$) is the radiation use
efficiency, $M_{leaf}$ is the leaf mass (kg), $SLA$ (m$^2$ kg$^{-1}$) is the
specific leaf area, and $C_{conversion}$ (kg mol$^{-1}$) is the amount of mass
gained by the plant per mol of assimilated carbon.

For carbon partitioning, we will calculate the rates of leaf and root mass
gain ($dM_{leaf} / dt$ and $dM_{root} / dt$, respectively, where $M_{root}$
is the root mass) as follows:
%
\begin{subequations}
 \label{eq:partitioning}
 \begin{align}
  \frac{dM_{leaf}}{dt} & = G \cdot f_{leaf} \\[5pt]
  \frac{dM_{root}}{dt} & = G \cdot f_{root}
 \end{align}
\end{subequations}
%
Here $f_{leaf}$ and $f_{root}$ are the fractions of carbon allocated to the
leaf and root, respectively. (To ensure that mass is conserved, the sum of
$f_{leaf}$ and $f_{root}$ should be 1.)

These equations represent the essential processes included in the model, but
they don't specify values for the parameters (like $SLA$ and $\alpha_{RUE}$) or
the initial values of the leaf and root masses. So, there are a few additional
equations required to fully describe the model. We can define the parameters and
initial values using simple equations as follows:
%
\begin{subequations}
  \label{eq:parameters}
  \begin{align}
    \alpha_{RUE}   & = 0.07 \\[5pt]
    SLA            & = 25   \\[5pt]
    f_{leaf}       & = 0.2  \\[5pt]
    f_{root}       & = 0.8  \\[5pt]
    C_{conversion} & = 0.03
  \end{align}
\end{subequations}
%
\begin{subequations}
  \label{eq:initial_values}
  \begin{align}
    M_{leaf}(0) & = 1 \\[5pt]
    M_{root}(0) & = 1
  \end{align}
\end{subequations}
%
We would like to consider the absorbed sunlight $Q$ as varying with time, so we
have specified its value at 1-second intervals throughout the course of one day
(Table \ref{tab_drivers}). The values follow a half-period sinusoidal light
profile throughout the day; this is not realistic, but it is sufficient for this
simple model. They are calculated according to the following equation, where the
time $t$ is expressed in seconds:
%
\begin{equation}
\label{eq:q}
Q(t) = \sin \left( \frac{t}{3600 \cdot 12} \cdot \pi \right) \cdot 2000 \times 10^{-6}.
\end{equation}

\begin{table}[ht]
  \begin{center}
    \begin{tabular}{@{}cc@{}}
      \toprule
      t        & Q                    \\ \midrule
      0        & 0                    \\
      1        & $7.2 \times 10^{-8}$ \\
      2        & $1.5 \times 10^{-7}$ \\
      \vdots   & \vdots               \\
      86400    & 0                    \\ \bottomrule
    \end{tabular}
  \end{center}
  \caption{
    Values of $Q(t)$ specified at 1-second intervals over the course of one day,
    as calculated using Equation \ref{eq:q}.
    \label{tab_drivers}
  }
\end{table}

Comparing Equations \ref{eq:photo} and \ref{eq:partitioning} with Figure
\ref{fig_conceptual_model}, we can recognize the essential features of the
conceptual diagram within the equations. For example, the absorbed sunlight $Q$
and the leaf mass $M_{leaf}$ are both inputs to the photosynthesis equations
(Equation \ref{eq:photo}), while the total rate of mass gain ($G$) is an input
to the partitioning equations (Equation \ref{eq:partitioning}). So, taken
together, Equations \ref{eq:photo}, \ref{eq:partitioning}, \ref{eq:parameters},
and \ref{eq:initial_values}, along with Table \ref{tab_drivers}, define the
model in a more concrete way than the conceptual diagram. However, we are still
not able to readily solve the model or use it to make predictions.

\subsubsection{The code level \label{sec_code_level}}

To finally make calculations, we need to translate these equations into a format
that can be understood by a computer. We can think of this as the most concrete
and specialized way to represent a model: the code level. For example, we can
define and solve the model in the \texttt{R} environment with the help of the
\texttt{deSolve} library (Figure \ref{fig_code_model}).

\begin{figure}[htbp]
<<code_level_example>>=
f <- function(t, y, p) {
  with(p, with(as.list(y), {
    A = Q(t) * alpha_rue          # mol / m^2 / s
    G = A * Leaf * SLA * C_conv  # kg
    dLeaf = G * f_leaf           # kg / s
    dRoot = G * f_root           # kg / s
    return(list(c(dLeaf, dRoot)))
  }))
}

initial_values <- c(
  Leaf = 1,  # kg
  Root = 1   # kg
)

params <- list(
  alpha_rue = 0.07,     # mol / mol
  SLA = 25,             # m^2 / kg
  f_leaf = 0.2,         # kg / ks
  f_root = 0.8,         # kg / kg
  C_conv = 0.03,        # kg / mol
  Q = function(time) {  # mol / m^2 / s
    sin(time / 3600 / 12 * pi * 2000e-6)
  }
)

time <- seq(0, 3600 * 12)  # s
solution <- lsodes(initial_values, time, f, params)
@
\caption{
  \texttt{R} code capable of solving the model defined in Sections
  \ref{sec_concept_level} and \ref{sec_equation_level}.
  \label{fig_code_model}
}
\end{figure}

It is clear that all the equations have made an appearance in this code, but
there are also several associated commands related to computer operations. The
requirement to add these commands can be a barrier to using a computational
model, since writing them requires specialized knowledge beyond just the
mathematical form of the equations.

Another important thing to notice is that in this code, we have lost most of the
flexibility that existed at the conceptual level. For example, at the conceptual
level (Figure \ref{fig_conceptual_model}), we specify that there is a
photosynthesis component, but we don't specify which one, and we are free to
mentally replace one model with another. In the code, however, we have clearly
specified that our photosynthesis model has a linear response to light, and it
is much more difficult to switch to a different model. (Perhaps in this case it
wouldn't be too much work, but more realistic models are typically much more
complicated, and the existing code is not always organized in a way that clearly
indicates which lines are related to which model component.)

\subsection{Making computer code more modular and flexible}

The main purpose of BioCro is to mitigate both issues with the code
representation of a model that were discussed in Section \ref{sec_code_level}---
the requirement for specialized computer programming knowledge and the lack of
flexibility---by (1) reducing the amount of ``extra stuff'' that must be written
when translating equations to the code level and (2) retaining the flexibility
of the concept level. In BioCro, this is accomplished by breaking up a model's
equations into reusable groups that we call \emph{modules}; this terminology was
chosen to emphasize that BioCro takes a \emph{modular} approach to modeling. (In
typical computer science terms, one might say that BioCro takes a highly
\emph{encapsulated} approach to modeling.) To understand what this means, let's
look at another short example showing how a typical piece of computer code can
be made more modular. This time, we will consider two hypothetical pieces of
code that represent models of soybean and miscanthus growth (Figure
\ref{fig_modular_code}).

\begin{figure}[htbp]
  \begin{center}
    \includegraphics[width=\textwidth]{workshop_I/modular_code.pdf}
    \caption{
      Diagram showing how models of soybean and miscanthus
      growth can be made more modular. \emph{Left}: In the original versions,
      both pieces of code contain identical sections for modeling carbon
      allocation. \emph{Center}: To reduce duplication, the code has been
      modified so that both crop models now use a separate function to implement
      the carbon allocation component. \emph{Right}: To make the code even more
      flexible, the crop models now allow the user to specify a carbon
      allocation function, which could be selected from multiple options.
    }
    \label{fig_modular_code}
  \end{center}
\end{figure}

\subsubsection{Identifying distinct concepts}

The key to making code more modular and flexible is to identify and separate
logically distinct concepts whenever possible. For example, let's say we notice
that the two growth models are using the same equations for allocating carbon
to the leaf and stem---perhaps both models use Equation \ref{eq:partitioning}
but with different parameters (see the left part of Figure
\ref{fig_modular_code}). Noticing overlaps like this one are not always easy
because the code may not be written in exactly the same way. For example, the
\texttt{R} code for soybean might look like this:

<<soybean_overlap_example, eval = FALSE>>=
leaf_mass_gain_rate <- total_mass_gain_rate * 0.2
root_mass_gain_rate <- total_mass_gain_rate * 0.8
@

\noindent while the \texttt{R} code used in the miscanthus version
might look like this:

<<miscanthus_overlap_example, eval = FALSE>>=
leaf_factor <- 0.3
dleaf_dt <- mass_gain * leaf_factor
droot_dt <- mass_gain * (1 - leaf_factor)
@

\noindent Thus, it can be time-consuming and difficult to identify cases of
overlap.

\subsubsection{Separating disctinct components}

Nevertheless, once an area of overlap has been detected, we can now recognize
that this carbon allocation concept is logically distinct from the rest of the
code and could be separated out. One way to do this would be to write a
dedicated function for carbon allocation, and have each crop model use this
function (see the center part of Figure \ref{fig_modular_code}). For example,
that function could look something like this:

<<allocation_overlap_example>>=
# This function partitions the crop's total rate of mass gain into its leaf and
# root compartments.
leaf_root_partitioning <- function(
  total_mass_gain_rate, # kg / s
  leaf_factor           # dimensionless
)
{
  return(list(
    leaf_mass_gain_rate = total_mass_gain_rate * leaf_factor,      # kg / s
    root_mass_gain_rate = total_mass_gain_rate * (1 - leaf_factor) # kg / s
  ))
}
@

\noindent There are two main advantages to this approach. One is that if the
allocation model needs to be updated (for example, to add another component such
as the stem), it only needs to be modified in one place. The other is that the
model is now easier to understand because the allocation component can easily be
examined on its own.

\subsubsection{Becoming even more flexible \label{sec_flexible_code}}

This level of modularity is common in modeling, but it is possible to go
further by recognizing that the carbon allocation code used in these models is
just one of many possible ways to model carbon allocation. In a more flexible
design, the code for the crop growth models could have an input argument that
specifies the particular allocation function to use. Then a modeler using the
code would be free to choose between multiple options if they are available (see
the right part of Figure \ref{fig_modular_code}).

By repeating this process, it would be possible to develop a very flexible type
of crop growth model, where a user is able to specify which photosynthesis
equations to use, which carbon allocation equations to use, or any other model
components that might have existed in the original versions of the models. But
why stop there? We could also separate out the parameters, initial values, and
drivers from the code that's used to combine the equations and run the model. We
could even stop requiring specific model components (e.g. photosynthesis or
carbon allocation) and allow the user to include any equations they would like
to use. The end result is an extremely flexible framework for defining and
running models of nearly any type. It could be used for simulating soybean or
miscanthus growth, or even something completely different like a gene
network.

It's important to realize that although there are numerous benefits to writing
modular code this way, it also makes other aspects of the code more difficult.
For example, if the user can specify \emph{any} allocation model, it's now
unclear which parameters would need to be specified by the user, since different
models might require different parameters. Thus, the parameter specification
needs to be very flexible, and the allocation model must be able to communicate
which inputs it requires. These kinds of issues prevent code like this from
being written very often.

\subsection{The BioCro framework}

In Section \ref{sec_flexible_code}, we discussed the benefits of using fully
modular code, but recognized out that writing it can be difficult. However, a
key feature of modular and flexible code is that it only needs to be written
once, and then it can be used for many different modeling purposes. This is
exactly what has been done with BioCro---beginning with several crop models that
had been written separately, all distinct components were identified and
separated, greatly reducing duplicated code and resulting in an extremely
flexible modeling framework.

In BioCro, a user can choose which model components they wish to use and supply
any other required specifications. Then, the BioCro framework takes care of
combining the equations and running the simulation (Section
\ref{sec_biocro_enable}). The framework is now quite complex, but most users
will never need to look at its code directly.

Returning to the simple model we discussed before, we can see how it looks in
BioCro (Figure \ref{fig_biocro_model}) and compare this version to the earlier
one (Figure \ref{fig_code_model}). The most important thing to notice is that
instead of directly specifying the equations for photosynthesis and carbon
partitioning, we can now refer to pre-defined sets of equations by their names -
in this case, \texttt{BioCro:example\_model\_mass\_gain} and
\texttt{BioCro:example\_model\_partitioning}. For this simple model, BioCro
doesn't actually save a lot of typing, but for more realistic models with
hundreds of equations, it is vastly faster and easier to define the model using
BioCro modules instead of doing it manually. (Of course, this requires that the
modules exist; writing them requires a bit of extra work, but the effort pays
off because they can be reused for many purposes.)

\begin{figure}[htbp]
<<biocro_example>>=
time <- seq(0, 3600 * 12)                  # s
Q <- sin(time / 3600 / 12 * pi * 2000e-6)  # mol / m^2 / s

solution_biocro <- run_biocro(
    parameters = list(
        alpha_rue = 0.07,  # mol / mol
        SLA = 25,          # m^2 / kg
        f_leaf = 0.2,      # kg / ks
        f_root = 0.8,      # kg / kg
        C_conv = 0.03,     # kg / mol
        timestep = 1
    ),
    initial_values = list(
        Leaf = 1,  # kg
        Root = 1   # kg
    ),
    drivers = data.frame(time = time, Q = Q),
    direct_module_names = 'BioCro:example_model_mass_gain',
    differential_module_names = 'BioCro:example_model_partitioning'
)
@
\caption{
  \texttt{R} code using the BioCro package to solve the model defined in
  Sections \ref{sec_concept_level} and \ref{sec_equation_level}.
  \label{fig_biocro_model}
}
\end{figure}

Besides shortening the code, BioCro allows us to think of the model at the
conceptual level---where model components are combined to form a larger model---
even though we are working at the coding level required to actually run a
simulation. This ability provides several important benefits to BioCro users,
such as the following:
\begin{itemize}
\item Defining a model is completely separate from solving it, allowing users to
      focus on biology instead of computer science.
\item Model components can easily be swapped for alternative versions to better
      match the available experimental inputs, to take advantage of new
      developments, or to compare alternative components.
\item BioCro modules can be developed privately so users can withhold access to
      model components until after publication.
\end{itemize}

\newpage

\setlength\bibitemsep{2.0\itemsep}
\printbibliography[heading=bibintoc]

\end{document}
