# This tests each module to make sure it can be instantiated and run
# Problems can arise e.g. if a module's get_outputs() or get_inputs() functions don't actually represent its real inputs and outputs

context("Test to make sure each module can be instantiated and run using default input parameters")

# A function that checks an error string to see if a quantity access error was found
quantity_access_error_found <- function(module_error) {
	quantity_access_error_string <- "Caught quantity access error"	# an exception generated by a quantity access error will contain this string
	if (grepl(quantity_access_error_string, module_error, fixed=TRUE) == TRUE) {
		return(TRUE)
	}
	else {
		return(FALSE)
	}
}

# A function that executes an R error action when a module produces a quantity access error
check_for_quantity_access_error <- function(module_error) {
	if (quantity_access_error_found(module_error)) {
		stop(module_error)
	}
}

# A function that executes an R error action when a module produces any other type of error
check_for_other_errors <- function(module_error) {
	if (module_error != "" && !quantity_access_error_found(module_error)) {
		stop(module_error)
	}
}

# A function that tries to instantiate and run a module, checking for any errors that may occur
run_module_trial <- function(module_name, description, error_message_testing_function)
{
	# Get the input parameters required by the module
	input_parameters <- get_module_info(module_name, verbose=FALSE)
	
	# All input parameters are set to 1.0 by default.
	# For certain modules, this produces error conditions.
	# To avoid this, we make case-by-case modifications
	if (module_name == "ball_berry_module") {
		input_parameters$atmospheric_co2_concentration = 2.0
	} else if (module_name == "ed_gas_concentrations") {
		input_parameters$assimilation_net = 0.5
		input_parameters$ball_berry_intercept = 0.01
		input_parameters$ball_berry_slope = 0.1
	} else if (module_name == "ed_canac_leaf") {
		input_parameters$collatz_PAR_flux = 10e-6
    } else if (module_name == "ten_layer_canopy_properties") {
        input_parameters$lnfun = 0
    }
	
	# Initialize the error message
	error_msg <- ""
	
	# Try to instantiate and run the module, storing any error messages
	tryCatch(
		{
			# Code to be executed initially
			output_parameters <- test_module(module_name, input_parameters)
		},
		error=function(cond) {
			# Code for handling errors
			error_msg <<- cond
		},
		warning=function(cond) {
			# Code for handling warnings
			error_msg <<- cond
		},
		finally={
			# Code to be executed after the initial code and handling
		}
	)
	
	test_that(description, {
		expect_error(error_message_testing_function(error_msg), regexp = NA)	# regexp = NA indicates that no error should be encountered
	})
}

# Test each module
all_modules <- get_all_modules()

for (module_name in all_modules) {
	# Test for quantity access errors at module startup
	description_access <- paste("The ", module_name, " module can properly access all of its required parameters", sep="")
	run_module_trial(module_name, description_access, check_for_quantity_access_error)

    if (module_name %in% c(
        'ed_c4_leaf_photosynthesis',
        'ed_c4_leaf_photosynthesis4',
        'ed_ten_layer_c4_canopy',
        ''))
    {
        print(paste('Test of', module_name, 'needs fixing.'))
        next
    }
	
	# Test for any other errors
	description_other <- paste("The ", module_name, " module can be instantiated and run without throwing any other exceptions", sep="")
	run_module_trial(module_name, description_other, check_for_other_errors)
}