module_library/c3_leaf_photosynthesis_test.o: \
 module_library/c3_leaf_photosynthesis_test.cpp \
 module_library/c3_leaf_photosynthesis_test.h \
 module_library/../framework/state_map.h \
 module_library/../framework/module.h \
 module_library/../framework/module_helper_functions.h \
 module_library/../framework/state_map.h \
 module_library/core/leaf_heat_balance.h \
 module_library/core/../../math/roots/onedim/dekker.h \
 module_library/core/../../math/roots/onedim/roots.h \
 module_library/core/../leaf_energy_balance.h module_library/c3photo.h \
 module_library/photosynthesis_outputs.h \
 module_library/c3_temperature_response.h
module_library/c3_leaf_photosynthesis_test.h:
module_library/../framework/state_map.h:
module_library/../framework/module.h:
module_library/../framework/module_helper_functions.h:
module_library/../framework/state_map.h:
module_library/core/leaf_heat_balance.h:
module_library/core/../../math/roots/onedim/dekker.h:
module_library/core/../../math/roots/onedim/roots.h:
module_library/core/../leaf_energy_balance.h:
module_library/c3photo.h:
module_library/photosynthesis_outputs.h:
module_library/c3_temperature_response.h:
