BioCro fitting, parameterization, and testing 
========================================================


```{r eval=FALSE, results='hide'}
install_bitbucket(repo="pecandb", username="dlebauer")
require(pecandb)
data(bety, package = "pecandb")
salix.yields <- get.yield.DT(list = bety)[genus == "Salix"]
save(salix.yields, salix.traits, salix.testyield, file = "inst/extdata/salix.RData")
```

```{r}
require(data.table)
require(lubridate)
require(ggplot2)
require(PEcAn.DB)
load(system.file("extdata", "salix.RData", package = "BioCro"))
settings.xml <- system.file("extdata/pecan.biocro.xml", 
                            package = "PEcAn.BIOCRO")

settings <- read.settings(settings.xml)
settings$database <- list(userid = "ebi_pecan", passwd = "hu2WHh32VC", database = "ebi_production", host = "ebi-forecast.igb.illinois.edu")

structure(list(userid = "bety", passwd = "bety", name = "bety", 
    location = "localhost"), .Names = c("userid", "passwd", "name", 
"location"))

```

```{r}
con <- query.base.con(settings=settings)
stest <- data.table(salix.testyield)
stest[,list(n = length(notes)), by = list(site, lat, lon, citations.author, citations.year, city, country, masl)]

x <- query.base(paste("select distinct citations.id, author, year, site_id  from citations join yields on yields.citation_id = citations.id where author in (", vecpaste(stest[,unique(citations.author)]),");"), con = con)

```

```{r fig.width=6, fig.height=6, echo=FALSE, results='hide'}



sites <- salix.yields[!is.na(lat), 
                      list(lat = unique(lat), lon = unique(lon), n = length(lat), city, sitename), by = site_id]

worldmap <- map_data("world") 
worldplot <- ggplot(worldmap) + 
  geom_path(aes(long, lat, group = group)) + 
  geom_point(data = sites, aes(lon, lat, size = 2*log(n)), color = "blue") + theme_bw() + ggtitle("Sites with Salix Yield Data") +
  geom_text(data = sites, hjust = 1, aes(lon, lat, label = paste(site_id, ifelse(is.na(city), substr(sitename, 1, 10), city))))

worldplot + xlim(-90, -60) + ylim(45,60)
worldplot + xlim(0, 30) + ylim(40,60)
sy <- salix.yields[site_id != 0 & !is.na(date),]
ggplot(sy, aes(ymd(date), mean)) + 
  geom_point(aes(color = as.factor(cultivar_id))) + facet_wrap(~city)

```

```{r fig.width=11, fig.height=3}
trait.summary <-  salix.traits[sort(n), 
                      list(n = length(site_id)), 
                               by = list(trait)]
trait.summary2 <- trait.summary[with(trait.summary, rank(n + rank(trait)/1000)),]
ggplot(data = trait.summary, aes(x = trait, y = n, order = n + rank(trait)/100)) + geom_point() + geom_linerange(aes(ymin = 0, ymax = n)) #+ coord_flip() + theme_bw()

```